use vulkano::{buffer::BufferContents, pipeline::graphics::vertex_input::Vertex as VertexInput};

// The next step is to create the shaders.
//
// The raw shader creation API provided by the vulkano library is unsafe for various reasons,
// so The `shader!` macro provides a way to generate a Rust module from GLSL source - in the
// example below, the source is provided as a string input directly to the shader, but a path
// to a source file can be provided as well. Note that the user must specify the type of shader
// (e.g. "vertex", "fragment", etc.) using the `ty` option of the macro.
//
// The items generated by the `shader!` macro include a `load` function which loads the shader
// using an input logical device. The module also includes type definitions for layout
// structures defined in the shader source, for example uniforms and push constants.
//
// A more detailed overview of what the `shader!` macro generates can be found in the
// vulkano-shaders crate docs. You can view them at https://docs.rs/vulkano-shaders/
pub mod vs {
    vulkano_shaders::shader! {
        ty: "vertex",
        src: r"
                #version 460

                layout(location = 0) in vec3 position;

                layout(location = 1) in vec3 color;

                layout(location = 0) out vec3 fragColor;

                layout(push_constant) uniform PushConstantData {
                    float time;
                } pc;


                void main() {
                    gl_Position = vec4(position*sin(pc.time), 1.0);
                    fragColor = color ;
                }
            ",
    }
}

pub mod fs {
    vulkano_shaders::shader! {
        ty: "fragment",
        src: r"
                #version 460

                layout(location = 0) in vec3 fragColor;

                layout(location = 0) out vec4 outColor;

                void main(){
                    outColor = vec4(fragColor, 1.0);
                }
            ",
    }
}

#[derive(BufferContents, VertexInput)]
#[repr(C)]
pub struct Vertex {
    #[format(R32G32B32_SFLOAT)]
    pub position: [f32; 3],
    #[format(R32G32B32_SFLOAT)]
    pub color: [f32; 3],
}

pub const VERTICES: [Vertex; 3] = [
    Vertex {
        position: [0.0, -0.25, 0.0],
        color: [1.0, 0.0, 0.0],
    },
    Vertex {
        position: [-0.5, 0.25, 0.0],
        color: [0.0, 1.0, 0.0],
    },
    Vertex {
        position: [0.5, 0.25, 0.0],
        color: [0.0, 0.0, 1.0],
    },
];

pub const INDICES: [u32; 3] = [0, 1, 1];
